spring:
   application:
      name: library

   datasource:
      url: jdbc:postgresql://localhost:5432/library
      username: postgres
      password: new_password
      driver-class-name: org.postgresql.Driver
   
   jpa: 
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate: 
         ddl-auto: update
      show-sql: true

   
   messages:
      basename: messages
      encoding: UTF-8

# jwt:
#    secret: rahasia
#    expiration: 3600000

server: 
   port: 8080
